--USE SQL_LIBRARY
--GO

--ALTER TABLE dbo.PRODUCTS ADD MANUFACTURER VARCHAR(20) NULL;

--ALTER TABLE dbo.Products DROP COLUMN MANUFACTURER;

ALTER TABLE dbo.PRODUCTS ADD Manufacturer VARCHAR(20) NULL;
